# Generated by Django 3.1.3 on 2021-04-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
